server:
     port: 8080
logging:
  level:
    org:
        springframework:
            web: INFO
error:
    include-message: always
    include-stacktrace: never
spring:
    datasource:
        url: jdbc:h2:mem:testdb
        username: 2JZ-GTE-DS32834-SA3-EXW7
        password: H4-8SURJWO-MM0234P-NH-FWQIE-A3-7ZPWXM-XX999P-9HKWB-ZYMZH-NE3RZ-R8XW7-T4JFGU-J9NFU-K9DJW
        driverClassName: org.h2.Driver
        continue-on-error: true
    h2:
     console.enable: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer:
        datasource-initialization: true
